### ISSUE TITLE
API redesign suggestion: get rid of `Dat` class

### ISSUE THREAD

**Issue by hossameldeen** [karissa/dat-api#23]
This issue is to suggest removing `Dat` class and to expose `Repo` directly.

Arguments I see for keeping it:

1. To make it possible to push default `opts` that apply to each newly-created `Repo`.
2. Having one `close` function.
3. `dat-js` is meant to be this one interface for the developer that has everything, such as this one `close`.

Arguments I see for removing it:

1. (1) could be dangerous as turned out in #20.
2. For (2), the design style of the dat ecosystem seems to prefer doing just one thing really well in each module/npm library.
3. For (3), actually, the developer ends up mostly using `Repo` APIs anyway. `create` and `get` could be static methods on `Repo` (like `DatArchive`).
4. As long as there's no shared state/variables between the repos, I think providing `Dat` adds complexity, and may actually encourage us to add shared state/variables when there could've been none.

So, my opinion would be to remove it.

What do you think?

**Comment by RangerMauve** [comment]
I like where you're coming from, but with the latest rewrite in #22, we actually do have shared state between the repos. The library will now make use of `discovery-swarm-web` which shares a single connection (for signaling and for the gateway) to reduce the load on the browser.

I've simplified the code a little and removed `Repo`, though. Now when you invoke `get()` it returns an archive directly instead of having an extra intermediate step.

**Comment by hossameldeen** [comment]
:+1: And happy for the news of getting back an archive directly (not sure what an archive is, but the fewer the concepts the better, I guess :-) )

I think this means we can close this.
