### ISSUE TITLE
hope more example

### ISSUE THREAD

**Issue by nolotus** [karissa/dat-api#5]
i plan build a app with dat-js ,i know dat-node ,but most user not know node ,and i hope user just open and use it  ,so,,just hope enhance dat-js

**Comment by joehand** [comment]
We transitioned away from using this library because of our [issues with webrtc](https://docs.datproject.org/faq#does-dat-use-webrtc). Since we do not use it actively, there will not be many examples to work from, sorry.

There are more examples of using [hyperdrive](https://github.com/mafintosh/hyperdrive) directly, which also works in the browser (dat-js is built on hyperdrive). Depending on your use case, that may be a better library to use.

Are you building an application that will only be used in the browser?

**Comment by joehand** [comment]
I should add that this library is currently outdated, see #4, so it will not work with the latest version of hyperdrive or be compatible with other applications.

**Comment by nolotus** [comment]
i plan build blog platform，i know beaker browser, and jekyll,  
but  it need down something  ,add something ,and it is a personal website  not have communicate with other people.
i plan build something ,it is  similar zeronet(i do not  like it ,i jsut want more pure protocol,such dat,), 
and  have : 
1  easy use it , just open browser ,and use it.  beacause more user more strong net.best compatible modern browser, no more need ,i know browser too many limit, maybe in the end just use electron build a  app.
2 distributed ，you know great fire wall ?  i hope ,even local area network ,it work .anything can not  stop it .

so  could you give me some advise ,
if i also build  in browser environment，not node.js environment.
